### ISSUE TITLE
Could not found Package with ‘framework-siwisdk @ ~0.5.0’

### ISSUE THREAD

**Issue by makbari2020** [siwiembedded/platform-siwigsm#2]
Hi
Today I multiple try to run an example of PlatformIO on VSCode but get an error:" Could not found Package with ‘framework-siwisdk @ 0.5.0 …"

Error:
> Could not install platform
> PIO Core Call Error: "Platform Manager: Installing git+https://github.com/siwiembedded/platform-siwigsm\r\nPlatform Manager: siwigsm @ 0.4.0+sha.14a8ff9 has been installed!\r\nTool Manager: toolchain-gccarmnoneeabi @ 1.80201.190214 is already installed\r\nTool Manager: Installing framework-siwisdk @ ~0.5.0\r\n\n\nError: Could not find the package with 'framework-siwisdk @ ~0.5.0' requirements for your system 'windows_amd64'"

FYI:
> Windows : 10 
> VSCode : v1.48.2
> PlatformIO: v1.10.2

What does this mean and how do I fix it?

**Comment by ajaybhargav** [comment]
I am not able to reproduce the issue. What is the PIO version?

**Comment by ajaybhargav** [comment]
Can you confirm if your issue is resolved with update?

**Comment by chandankmr02** [comment]
I am also facing the same issue while installing platform-siwigsm. 
I am using Win 10
Platform IO: Core 5.0.1 Home 3.3.0
VS Code: 1.49.1

Please help me resolve the issue.

![image](https://user-images.githubusercontent.com/42230174/94123168-11b42680-fe71-11ea-9b75-abbe0fc1dcb4.png)

**Comment by ajaybhargav** [comment]
Hi, I figured out the issue, it due to release archive name change done by github which breaks the installation. I have fixed the manifest now. Please try again and let me know. It may be possible that URL is cached so try to open URL in browser first to see if links are updated:
https://siwiembedded.github.io/manifest.json

SDK link should reflect: https://siwiembedded.github.io/siwisdk-0.5.2.tar.gz

**Comment by chandankmr02** [comment]
Still facing the same issue.

Check this snapshot:

![image](https://user-images.githubusercontent.com/42230174/94282157-1fe76d00-ff6d-11ea-8e74-aed85e8a58a2.png)

**Comment by ajaybhargav** [comment]
Looks like platformio has made major changes in their new version. I will have to register siwigsm to PlatformIO registry to it working. Please wait until I complete the process and let you guys know once its done.

**Comment by ajaybhargav** [comment]
The platform version has been updated. Everything should work now.
I have also submitted siwigsm to PlatformIO Platform registry, once accepted you will be able to install platform from directly within the PlatformIO IDE instead of doing advanced installation process.
I will also update the docs soon.

**Comment by ajaybhargav** [comment]
![image](https://user-images.githubusercontent.com/927133/94585449-a8cc1480-029d-11eb-813f-7b049d710345.png)
You can now directly install form PlatformIO IDE by searching under platform. No need to advanced installation anymore.
